### ISSUE TITLE
Error while starting up action

### ISSUE THREAD

**Issue by Mnigos** [BerniWittmann/background-server-action#96]
```
Current runner version: '2.296.1'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `BerniWittmann/background-server-action@latest`, unable to find version `latest`
```

**Comment by BerniWittmann** [comment]
I finally had the chance to work on this repo again and this issue has been fixed in the latest version. See [latest release ](https://github.com/BerniWittmann/background-server-action/releases/tag/v1.1.0) notes with more info 

Ensure you have set `uses: BerniWittmann/background-server-action@v1` or `BerniWittmann/background-server-action@v1.1.0`
